<?php
//Implémentation des constantes
const EXIT_CODE_OK = 0;
const EXIT_CODE_ACTION_MISSING = 1;
const EXIT_CODE_INCORRECT_PARAMETTER = 2;
const EXIT_CODE_ERROR_API_EXTERNAL = 3;
const EXIT_CODE_UNKNOW_ACTION = 4;
const EXIT_CODE_UNKNOW_ID_USER = 5;
const EXIT_CODE_INCORRECT_ID_USER = 6;
const EXIT_CODE_UNKNOW_CARDS = 7;
const EXIT_CODE_INCORRECT_CARDS = 8;
const EXIT_CODE_UNKNOW_CARDS_PARAMETTER = 9;
const EXIT_CODE_CARDS_IS_MISSING_IN_DB = 10;
const EXIT_CODE_RANDOM_CARD_IS_NULL = 11;
const EXIT_CODE_ERROR_INSERTION_IN_DB = 12;
const EXIT_CODE_INCORRECT_MONEY_READ = 13;
const EXIT_CODE_INCORRECT_TYPE_REQUEST = 14;
const EXIT_CODE_INVALID_URI = 15;
const EXIT_CODE_TOO_LONG_URI = 16;
const EXIT_CODE_UNKNOW_VALUE_PARAMETTER = 17;
const EXIT_CODE_INCORRECT_MONEY_SETTER = 18;
const EXIT_CODE_INCORRECT_USER_READ = 19;
const EXIT_CODE_MISSING_PARAMETTER = 20;
const EXIT_CODE_ERROR_SQL = 21;
const EXIT_CODE_NO_IMPLEMENTED_FUNCTION = 99;
